version: '3'

services:
  mongodb:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root


  backend:
    build: .
    command: go run .
    ports:
      - 8080:8080
    depends_on:
      - mongodb