version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin


  backend:
    build: .
    command: go run .
    ports:
      - 8000:8000
    depends_on:
      - mongodb