version: '3'

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - 27017:27017
    command: mongosh


  backend:
    build: .
    command: go run .
    ports:
      - 8080:8080
    depends_on:
      - mongodb